name: Terraform on Self-Hosted Runner (Docker Desktop)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Docker Apply
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
      
    - name: Terraform Format Check
      working-directory: ./terraform
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./terraform
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve


# Finished
